### ISSUE TITLE
Adicionando Indice Geral

### ISSUE THREAD

**Issue by sergioSHKLR** [JhonnyBn/ConversoesLDE#1]
Em primeiro lugar, parabéns pela conversão!

Agora estou trabalhando no Indice Geral do LDE e vou criar _anchor names_ para cada uma das 1019 questões e subquestões. Só assim conseguirei fazer o link entre Indice e conteudo.

Isso não irá atrapalhar sua solução?

**Comment by JhonnyBn** [comment]
> Em primeiro lugar, parabéns pela conversão!

Obrigado!

> Agora estou trabalhando no Indice Geral do LDE e vou criar _anchor names_ para cada uma das 1019 questões e subquestões. Só assim conseguirei fazer o link entre Indice e conteudo.

Isso seria feito da mesma forma que as primeiras 34 questões?
Exemplo: Ao invés de "1.", temos "[1](#lde.q1)."

> Isso não irá atrapalhar sua solução?

Sim, e não. Isso deixaria a solução mais complexa, mas não atrapalharia per se
Porém creio que deixar o texto simples e gerar esse índice automaticamente usando os scripts seria melhor

**Comment by JhonnyBn** [comment]
Acabei de enviar um update que lida com hyperlink das questões! Dê uma olhada no [output](https://github.com/JhonnyBn/ConversoesLDE/blob/main/output.md) e veja se é isso que espera

**Comment by sergioSHKLR** [comment]
> Acabei de enviar um update que lida com hyperlink das questões! Dê uma olhada no [output](https://github.com/JhonnyBn/ConversoesLDE/blob/main/output.md) e veja se é isso que espera

Isso mesmo! Mas como conversamos ontem, vamos deixar o hyperlink de lado por enquanto e concentrar no código lde.X.XX.X e lde.qX. Obrigado, João!
